rtt_roscomm: fixed compilation of service plugins with Clang (regression from https://github.com/orocos/rtt_ros_integration/pull/123)
Clang seems to handle SFINAE differently than gcc and compilation of generated service proxy plugins failed with errors like:

In file included from rtt_diagnostic_msgs/diagnostic_msgs_service_proxies/rtt_rosservice_proxies.cpp:7:
rtt_roscomm/rtt_rosservice_proxy.h:99:30: error: implicit instantiation of undefined template 'ROSServiceServerOperationCallerWrapper<diagnostic_msgs::AddDiagnostics, 1>'